---
project_name: "hugo-portfolio"
domain_name: "example.com"

aws_region: "eu-north-1"
bucket_subdomain: "www"

keep_acm: true
keep_route53: true
keep_s3: false
keep_cloudfront: false
keep_github_deployer: false
keep_iam_role: false

common_tags:
  Project: "{{ project_name }}"

github_deployer_enabled: false
github_account_name: "YOUR_GITHUB_NAME_OR_ORG"
github_repo_name: "YOUR_REPO"
github_repo_branch: "main"
