---
project_name: "hugo-portfolio"
domain_name: "ruminahui.ch"

aws_region: "eu-north-1"
bucket_subdomain: "www"

keep_acm: true
keep_route53: true
keep_s3: false
keep_cloudfront: false
keep_github_deployer: false
keep_iam_role: false

common_tags:
  Project: "HugoPortfolioHosting"

github_deployer_enabled: true
github_account_name: "RuminahuiM"
github_repo_name: "portfolio"
github_repo_branch: "test-s3upload01"
