---
project_name: "hugo-portfolio"
domain_name: "ruminahui.ch"

aws_region: "eu-north-1"
bucket_subdomain: "www"

common_tags:
  Project: "HugoPortfolioHosting"

github_deployer_enabled: true
github_account_name: "RuminahuiM"
github_repo_name: "portfolio"
github_repo_branch: "test-s3upload01"
